const express=require('express');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const User=require('../models/User');
const {requireAuth}=require('../middleware/auth');
const router=express.Router();
function publicUser(u){return {id:u._id.toString(),name:u.name,email:u.email,phone:u.phone||'',role:u.role,isVerified:u.isVerified};}
function signToken(u){return jwt.sign({userId:u._id.toString(),role:u.role},process.env.JWT_SECRET,{expiresIn:'7d'});}
router.post('/register',async(req,res)=>{try{const {name,email,phone,password,role}=req.body;if(!name||!email||!password)return res.status(400).json({message:'Name, email and password are required.'});const normalized=email.toLowerCase().trim();if(await User.exists({email:normalized}))return res.status(409).json({message:'An account with this email already exists.'});const user=await User.create({name:name.trim(),email:normalized,phone:phone||'',passwordHash:await bcrypt.hash(password,10),role:role==='owner'?'owner':'user'});res.status(201).json({token:signToken(user),user:publicUser(user)});}catch(e){res.status(500).json({message:'Registration failed. Please try again.'});}});
router.post('/login',async(req,res)=>{try{const login=(req.body.email||req.body.userId||'').trim().toLowerCase(),password=req.body.password;if(!login||!password)return res.status(400).json({message:'Email/User ID and password are required.'});let user=await User.findOne({email:login});if(!user&&/^[a-f0-9]{24}$/i.test(login))user=await User.findById(login);if(!user||!(await bcrypt.compare(password,user.passwordHash)))return res.status(401).json({message:'Invalid login details.'});res.json({token:signToken(user),user:publicUser(user)});}catch(e){res.status(500).json({message:'Login failed. Please try again.'});}});
router.post('/setup-admin',async(req,res)=>{try{if(await User.exists({role:'admin'}))return res.status(409).json({message:'An admin already exists. Use admin login.'});if(!process.env.ADMIN_SETUP_KEY||req.body.setupKey!==process.env.ADMIN_SETUP_KEY)return res.status(403).json({message:'Invalid admin setup key.'});const {name,email,phone,password}=req.body;if(!name||!email||!password)return res.status(400).json({message:'Name, email and password are required.'});const normalized=email.toLowerCase().trim();if(await User.exists({email:normalized}))return res.status(409).json({message:'Email already exists.'});const user=await User.create({name:name.trim(),email:normalized,phone:phone||'',passwordHash:await bcrypt.hash(password,10),role:'admin',isVerified:true});res.status(201).json({token:signToken(user),user:publicUser(user),message:'Admin created.'});}catch(e){res.status(500).json({message:'Admin creation failed.'});}});
router.get('/me',requireAuth,async(req,res)=>res.json({user:publicUser(req.user)}));
module.exports=router;
