const express=require('express');const mongoose=require('mongoose');const crypto=require('crypto');const Vehicle=require('../models/Vehicle');const Booking=require('../models/Booking');const Agreement=require('../models/Agreement');const MonthlyBookingCounter=require('../models/MonthlyBookingCounter');const {requireAuth}=require('../middleware/auth');const router=express.Router();
function monthKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;}
async function reserveSlot(userId,key,session){let c=await MonthlyBookingCounter.findOne({userId,monthKey:key}).session(session);if(c){if(c.count>=2)throw Object.assign(new Error('You can make a maximum of 2 bookings per month.'),{code:'MONTHLY_LIMIT'});c.count++;await c.save({session});return c.count;}const [y,m]=key.split('-').map(Number);const count=await Booking.countDocuments({userId,createdAt:{$gte:new Date(y,m-1,1),$lt:new Date(y,m,1)},status:{$in:['pending','payment_pending','confirmed','completed']}}).session(session);if(count>=2)throw Object.assign(new Error('You can make a maximum of 2 bookings per month.'),{code:'MONTHLY_LIMIT'});await MonthlyBookingCounter.create([{userId,monthKey:key,count:count+1}],{session});return count+1;}
async function createAgreement(id){const b=await Booking.findById(id).populate('userId','name email phone').populate({path:'vehicleId',populate:{path:'ownerId',select:'name email phone'}});if(!b)throw new Error('Booking not found.');const existing=await Agreement.findOne({bookingId:b._id});const a={bookingId:b._id,agreementId:existing?.agreementId||`AG-${b._id.toString().slice(-8).toUpperCase()}`,renterName:b.userId.name,renterEmail:b.userId.email,ownerName:b.vehicleId?.ownerId?.name||'Vehicle Owner',ownerEmail:b.vehicleId?.ownerId?.email||'',vehicleName:b.vehicleId?.name||'VROOMY Vehicle',vehicleNumberPlate:b.vehicleId?.numberPlate||'',pickupDate:b.startDate,returnDate:b.endDate,rentalAmount:b.totalAmount,paymentStatus:'PAID',acceptedByUser:true,acceptedAt:new Date(),termsVersion:'v1'};return existing?Agreement.findOneAndUpdate({bookingId:b._id},a,{new:true,runValidators:true}):Agreement.create(a);}
function pdfText(v){return String(v??'').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');}
function makePdf(a){const lines=['VROOMY RENTAL AGREEMENT','',`Agreement ID: ${a.agreementId}`,`Booking ID: ${a.bookingId}`,'',`Renter: ${a.renterName}`,`Owner: ${a.ownerName}`,`Vehicle: ${a.vehicleName}`,`Vehicle Number: ${a.vehicleNumberPlate||'Not provided'}`,`Pickup: ${new Date(a.pickupDate).toLocaleString('en-IN')}`,`Return: ${new Date(a.returnDate).toLocaleString('en-IN')}`,`Rental Amount: Rs. ${a.rentalAmount}`,`Payment Status: ${a.paymentStatus}`,'','Generated from the VROOMY verified booking record.'];const c=['BT','/F1 18 Tf','50 760 Td',`(${pdfText(lines[0])}) Tj`,'/F1 10 Tf'];for(const l of lines.slice(1)){c.push('0 -22 Td',`(${pdfText(l)}) Tj`);}c.push('ET');const objs=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${Buffer.byteLength(c.join('\n'))} >>\nstream\n${c.join('\n')}\nendstream`];let pdf='%PDF-1.4\n',off=[0];objs.forEach((o,i)=>{off[i+1]=Buffer.byteLength(pdf);pdf+=`${i+1} 0 obj\n${o}\nendobj\n`;});const x=Buffer.byteLength(pdf);pdf+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`;for(let i=1;i<off.length;i++)pdf+=`${String(off[i]).padStart(10,'0')} 00000 n \n`;pdf+=`trailer\n<< /Size ${objs.length+1} /Root 1 0 R >>\nstartxref\n${x}\n%%EOF`;return Buffer.from(pdf,'binary');}
router.post('/',requireAuth,async(req,res)=>{try{const {vehicleId,startDate,endDate,estimatedKm=0,panNumber='',drivingLicenseNumber=''}=req.body;if(!mongoose.isValidObjectId(vehicleId))return res.status(400).json({message:'Valid vehicleId is required.'});const pan=String(panNumber).trim().toUpperCase(),dl=String(drivingLicenseNumber).trim().toUpperCase();if(!/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(pan))return res.status(400).json({message:'Enter a valid PAN number (example: ABCDE1234F).'});if(dl.length<6||dl.length>25)return res.status(400).json({message:'Enter a valid driving licence number.'});const start=new Date(startDate),end=new Date(endDate);if(Number.isNaN(start.getTime())||Number.isNaN(end.getTime())||end<=start)return res.status(400).json({message:'Valid start and end dates are required.'});if(start<=new Date())return res.status(400).json({message:'Booking start time must be in the future.'});const vehicle=await Vehicle.findOne({_id:vehicleId,status:'available',verified:true});if(!vehicle)return res.status(404).json({message:'Vehicle is not available for booking.'});const overlap=await Booking.findOne({vehicleId,status:{$in:['pending','payment_pending','confirmed']},startDate:{$lt:end},endDate:{$gt:start}});if(overlap)return res.status(409).json({message:'Vehicle is already booked for part of this time.'});const hours=Math.max(1,Math.ceil((end-start)/3600000)),km=Math.max(0,Number(estimatedKm)||0),extraKm=hours>=24?Math.max(0,km-300):0,total=hours*vehicle.price+extraKm*10,key=monthKey();const session=await mongoose.startSession();let b;try{await session.withTransaction(async()=>{const fresh=await Booking.findOne({vehicleId,status:{$in:['pending','payment_pending','confirmed']},startDate:{$lt:end},endDate:{$gt:start}}).session(session);if(fresh)throw Object.assign(new Error('Vehicle is already booked for part of this time.'),{code:'OVERLAP'});const slot=await reserveSlot(req.user._id,key,session);b=(await Booking.create([{userId:req.user._id,vehicleId,startDate:start,endDate:end,estimatedKm:km,hours,totalAmount:total,monthKey:key,monthlySlot:slot,panNumber:pan,drivingLicenseNumber:dl,paymentMethod:'demo',status:'payment_pending',paymentStatus:'pending',commissionRate:10}],{session}))[0];});}catch(e){return res.status(e.code==='MONTHLY_LIMIT'?429:e.code==='OVERLAP'?409:400).json({message:e.message});}finally{await session.endSession();}const populated=await Booking.findById(b._id).populate('vehicleId','name type location price image').lean();res.status(201).json({...populated,id:b._id.toString(),payment:{method:'demo',amount:Math.round(total*100),currency:'INR',displayAmount:total}});}catch(e){res.status(400).json({message:e.message});}});
router.post('/:id/payment-demo',requireAuth,async(req,res)=>{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:'Invalid booking id.'});const b=await Booking.findOne({_id:req.params.id,userId:req.user._id,status:'payment_pending',paymentStatus:'pending'});if(!b)return res.status(404).json({message:'Pending booking not found.'});const commission=Math.round(b.totalAmount*0.10*100)/100,ownerEarning=Math.round((b.totalAmount-commission)*100)/100,ref=`VROOMY-DEMO-${crypto.randomBytes(8).toString('hex').toUpperCase()}`;const updated=await Booking.findByIdAndUpdate(b._id,{paymentStatus:'paid',status:'confirmed',paymentReference:ref,platformCommission:commission,ownerEarning},{new:true});const agreement=await createAgreement(updated._id);res.json({success:true,message:'Payment successful. Booking confirmed.',booking:{...updated.toObject(),id:updated._id.toString()},agreement,paymentReference:ref});});
router.post('/:id/payment-failed',requireAuth,async(req,res)=>{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:'Invalid booking id.'});const b=await Booking.findOneAndUpdate({_id:req.params.id,userId:req.user._id,status:'payment_pending'},{paymentStatus:'failed',status:'cancelled',cancelledBy:req.user._id,cancelReason:'Payment cancelled'},{new:true});if(!b)return res.status(404).json({message:'Pending booking not found.'});await MonthlyBookingCounter.findOneAndUpdate({userId:b.userId,monthKey:b.monthKey,count:{$gt:0}},{$inc:{count:-1}});res.json({success:true,message:'Payment cancelled. Booking not confirmed.'});});
router.post('/:id/cancel',requireAuth,async(req,res)=>{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:'Invalid booking id.'});const b=await Booking.findById(req.params.id).populate('vehicleId');if(!b)return res.status(404).json({message:'Booking not found.'});const isUser=b.userId.toString()===req.user._id.toString(),isOwner=b.vehicleId?.ownerId?.toString()===req.user._id.toString();if(req.user.role!=='admin'&&!isUser&&!isOwner)return res.status(403).json({message:'You cannot cancel this booking.'});if(['cancelled','completed'].includes(b.status))return res.status(400).json({message:'This booking is already closed.'});if(new Date(b.startDate)<=new Date())return res.status(400).json({message:'Started or past bookings cannot be cancelled.'});b.status='cancelled';b.cancelledBy=req.user._id;b.cancelReason=req.body.reason||`Cancelled by ${req.user.role}`;if(b.paymentStatus==='paid'){b.paymentStatus='refunded';b.refundAmount=b.totalAmount;b.platformCommission=0;b.ownerEarning=0;}else{b.paymentStatus='failed';await MonthlyBookingCounter.findOneAndUpdate({userId:b.userId,monthKey:b.monthKey,count:{$gt:0}},{$inc:{count:-1}});}await b.save();res.json({message:'Booking cancelled successfully. Demo payment is marked refunded when applicable.',booking:{...b.toObject(),id:b._id.toString()}});});
router.get('/owner/summary',requireAuth,async(req,res)=>{
 if(!['owner','admin'].includes(req.user.role)) return res.status(403).json({message:'Owner access required.'});
 const vehicleQuery=req.user.role==='admin'?{}:{ownerId:req.user._id};
 const vehicles=await Vehicle.find(vehicleQuery).select('_id name').lean();
 const ids=vehicles.map(v=>v._id);
 if(!ids.length) return res.json({grossRevenue:0,totalEarnings:0,commission:0,paidBookings:0,pendingPayments:0,pendingPaymentCount:0,activeBookings:0,rentedVehicles:0,revenuePerVehicle:[],recent:[]});
 const match={vehicleId:{$in:ids}};
 const [paid,pending,active,paidCount,recent]=await Promise.all([
   Booking.aggregate([{$match:{...match,paymentStatus:'paid'}},{$group:{_id:null,gross:{$sum:'$totalAmount'},earnings:{$sum:'$ownerEarning'},commission:{$sum:'$platformCommission'}}}]),
   Booking.aggregate([{$match:{...match,paymentStatus:'pending',status:'payment_pending'}},{$group:{_id:null,total:{$sum:'$totalAmount'},count:{$sum:1}}}]),
   Booking.countDocuments({...match,status:'confirmed'}),
   Booking.countDocuments({...match,paymentStatus:'paid'}),
   Booking.find(match).populate('userId','name email').populate('vehicleId','name type').sort({createdAt:-1}).limit(10).lean()
 ]);
 const rev=await Booking.aggregate([
   {$match:{...match,paymentStatus:'paid'}},
   {$group:{_id:'$vehicleId',gross:{$sum:'$totalAmount'},earnings:{$sum:'$ownerEarning'},commission:{$sum:'$platformCommission'},paidBookings:{$sum:1}}},
   {$sort:{earnings:-1}}
 ]);
 const names=Object.fromEntries(vehicles.map(v=>[v._id.toString(),v.name]));
 res.json({
   grossRevenue:paid[0]?.gross||0,totalEarnings:paid[0]?.earnings||0,commission:paid[0]?.commission||0,
   paidBookings:paidCount,pendingPayments:pending[0]?.total||0,pendingPaymentCount:pending[0]?.count||0,
   activeBookings:active,rentedVehicles:rev.length,
   revenuePerVehicle:rev.map(x=>({...x,vehicleId:x._id.toString(),vehicleName:names[x._id.toString()]||'Vehicle'})),
   recent:recent.map(b=>({...b,id:b._id.toString(),userId:b.userId?{name:b.userId.name,email:b.userId.email}:null,vehicleId:b.vehicleId?{name:b.vehicleId.name,type:b.vehicleId.type}:null}))
 });
});
router.get('/owner/my',requireAuth,async(req,res)=>{
 if(!['owner','admin'].includes(req.user.role)) return res.status(403).json({message:'Owner access required.'});
 const vehicleIds=(await Vehicle.find(req.user.role==='admin'?{}:{ownerId:req.user._id}).select('_id').lean()).map(v=>v._id);
 const docs=await Booking.find({vehicleId:{$in:vehicleIds}}).populate('userId','name email').populate('vehicleId','name type location').sort({createdAt:-1}).lean();
 res.json(docs.map(b=>({...b,id:b._id.toString(),userId:b.userId?{id:b.userId._id.toString(),name:b.userId.name,email:b.userId.email}:null,vehicleId:b.vehicleId?{id:b.vehicleId._id.toString(),name:b.vehicleId.name,type:b.vehicleId.type,location:b.vehicleId.location}:null})));
});

router.get('/my',requireAuth,async(req,res)=>{const docs=await Booking.find({userId:req.user._id}).populate('vehicleId','name type location image price numberPlate ownerId').sort({createdAt:-1}).lean();res.json(docs.map(b=>({...b,id:b._id.toString(),userId:b.userId.toString(),vehicleId:b.vehicleId?{id:b.vehicleId._id.toString(),name:b.vehicleId.name,type:b.vehicleId.type,location:b.vehicleId.location,image:b.vehicleId.image,price:b.vehicleId.price,numberPlate:b.vehicleId.numberPlate||'',ownerId:b.vehicleId.ownerId?.toString()}:null})));});
router.get('/my-agreements',requireAuth,async(req,res)=>{const ids=(await Booking.find({userId:req.user._id}).select('_id').lean()).map(x=>x._id);const docs=await Agreement.find({bookingId:{$in:ids}}).sort({createdAt:-1}).lean();res.json(docs.map(a=>({...a,id:a._id.toString(),bookingId:a.bookingId.toString()})));});
router.get('/admin/all',requireAuth,async(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({message:'Admin access required.'});const docs=await Booking.find({}).populate('userId','name email').populate('vehicleId','name type location ownerId').sort({createdAt:-1}).lean();res.json(docs.map(b=>({...b,id:b._id.toString()})));});
router.get('/:id/agreement',requireAuth,async(req,res)=>{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:'Invalid booking id.'});const b=await Booking.findById(req.params.id);if(!b)return res.status(404).json({message:'Booking not found.'});if(req.user.role!=='admin'&&b.userId.toString()!==req.user._id.toString())return res.status(403).json({message:'Not allowed.'});const a=await Agreement.findOne({bookingId:b._id});if(!a)return res.status(404).json({message:'Agreement has not been generated yet.'});const pdf=makePdf(a.toObject());res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename="${a.agreementId}.pdf"`);res.send(pdf);});
module.exports=router;
