const express=require('express');const mongoose=require('mongoose');const crypto=require('crypto');const Ride=require('../models/Ride');const RideBooking=require('../models/RideBooking');const {requireAuth}=require('../middleware/auth');const router=express.Router();
router.post('/',requireAuth,async(req,res)=>{try{const {rideId,seats}=req.body;if(!mongoose.isValidObjectId(rideId))return res.status(400).json({message:'Valid rideId is required.'});const n=Number(seats);if(!Number.isInteger(n)||n<1||n>6)return res.status(400).json({message:'Choose a valid number of seats.'});const ride=await Ride.findOne({_id:rideId,status:'approved'});if(!ride)return res.status(404).json({message:'Ride is not available.'});if(ride.driverId.toString()===req.user._id.toString())return res.status(400).json({message:'You cannot book your own ride.'});const booked=await RideBooking.aggregate([{$match:{rideId:ride._id,status:{$in:['payment_pending','confirmed']} }},{$group:{_id:null,seats:{$sum:'$seats'}}}]);const remaining=ride.seats-(booked[0]?.seats||0);if(n>remaining)return res.status(409).json({message:`Only ${remaining} seat(s) are available.`});const total=n*ride.price;const b=await RideBooking.create({userId:req.user._id,rideId:ride._id,seats:n,totalAmount:total,commissionRate:10,status:'payment_pending',paymentStatus:'pending'});res.status(201).json({...b.toObject(),id:b._id.toString(),payment:{amount:total,currency:'INR',displayAmount:total}});}catch(e){res.status(400).json({message:e.message});}});
router.post('/:id/payment-demo',requireAuth,async(req,res)=>{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:'Invalid ride booking id.'});const b=await RideBooking.findOne({_id:req.params.id,userId:req.user._id,status:'payment_pending',paymentStatus:'pending'});if(!b)return res.status(404).json({message:'Pending ride booking not found.'});const ref='VROOMY-RIDE-'+crypto.randomBytes(6).toString('hex').toUpperCase();const commission=Math.round(b.totalAmount*0.10*100)/100;const driverEarning=Math.round((b.totalAmount-commission)*100)/100;const updated=await RideBooking.findByIdAndUpdate(b._id,{status:'confirmed',paymentStatus:'paid',paymentReference:ref,platformCommission:commission,driverEarning},{new:true});res.json({success:true,message:'Ride payment successful.',booking:{...updated.toObject(),id:updated._id.toString()},paymentReference:ref});});
router.post('/:id/cancel',requireAuth,async(req,res)=>{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:'Invalid ride booking id.'});const b=await RideBooking.findById(req.params.id).populate('rideId');if(!b)return res.status(404).json({message:'Ride booking not found.'});const isUser=b.userId.toString()===req.user._id.toString();const isDriver=b.rideId?.driverId?.toString()===req.user._id.toString();if(req.user.role!=='admin'&&!isUser&&!isDriver)return res.status(403).json({message:'You cannot cancel this booking.'});if(['cancelled','completed'].includes(b.status))return res.status(400).json({message:'This booking is already closed.'});if(b.rideId?.date&&new Date(b.rideId.date)<=new Date())return res.status(400).json({message:'Past rides cannot be cancelled.'});b.status='cancelled';b.cancelledBy=req.user._id;b.cancelReason=req.body.reason||'Cancelled by user';if(b.paymentStatus==='paid'){b.paymentStatus='refunded';b.refundAmount=b.totalAmount;b.platformCommission=0;b.driverEarning=0;}else b.paymentStatus='failed';await b.save();res.json({message:'Ride booking cancelled.',booking:{...b.toObject(),id:b._id.toString()}});});
router.get('/driver/my',requireAuth,async(req,res)=>{
 if(!['owner','admin','user'].includes(req.user.role)) return res.status(403).json({message:'Access denied.'});
 const rides=await Ride.find(req.user.role==='admin'?{}:{driverId:req.user._id}).select('_id from to date time vehicle').lean();
 const ids=rides.map(r=>r._id);
 const docs=await RideBooking.find({rideId:{$in:ids}}).populate('userId','name email').populate('rideId','from to date time vehicle driverId').sort({createdAt:-1}).lean();
 res.json(docs.map(b=>({...b,id:b._id.toString(),userId:b.userId?{id:b.userId._id.toString(),name:b.userId.name,email:b.userId.email}:null})));
});

router.get('/my',requireAuth,async(req,res)=>{const docs=await RideBooking.find({userId:req.user._id}).populate({path:'rideId',populate:{path:'driverId',select:'name email'}}).sort({createdAt:-1}).lean();res.json(docs.map(b=>({...b,id:b._id.toString(),rideId:b.rideId?{id:b.rideId._id.toString(),from:b.rideId.from,to:b.rideId.to,date:b.rideId.date,time:b.rideId.time,vehicle:b.rideId.vehicle,driver:b.rideId.driver,seats:b.rideId.seats,price:b.rideId.price}:null})));});
router.get('/admin/all',requireAuth,async(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({message:'Admin access required.'});const docs=await RideBooking.find({}).populate('userId','name email').populate('rideId','from to date time vehicle').sort({createdAt:-1}).lean();res.json(docs.map(b=>({...b,id:b._id.toString()})));});
module.exports=router;
