document.addEventListener('DOMContentLoaded',async()=>{
 const el=document.getElementById('bookingList'); if(!el)return; if(!requireLogin())return;
 let rentals=[],rides=[],incomingRentals=[],incomingRides=[];
 try{[rentals,rides]=await Promise.all([api('/bookings/my'),api('/ride-bookings/my')]);const u=getStoredUser();if(u?.role==='owner'||u?.role==='admin'){[incomingRentals,incomingRides]=await Promise.all([api('/bookings/owner/my'),api('/ride-bookings/driver/my')]);}}catch(e){el.innerHTML=`<div class="empty">${escapeHtml(e.message)}</div>`;return}
 let items=[...rentals.map(x=>({...x,kind:'Rental',mine:true})),...rides.map(x=>({...x,kind:'Shared Ride',mine:true}))].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));
 const incoming=[...incomingRentals.map(x=>({...x,kind:'Incoming Rental',mine:false})),...incomingRides.map(x=>({...x,kind:'Incoming Ride',mine:false}))].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));
 const render=status=>{const visible=status==='Upcoming'?items.filter(x=>['pending','payment_pending','confirmed'].includes(x.status)):status==='Completed'?items.filter(x=>x.status==='completed'):items.filter(x=>x.status==='cancelled');el.innerHTML=visible.length?visible.map(x=>{const name=x.kind==='Rental'?(x.vehicleId?.name||'Vehicle rental'):`${x.rideId?.from||''} → ${x.rideId?.to||''}`;const canCancel=['pending','payment_pending','confirmed'].includes(x.status);return `<article class="booking-row"><div><span class="pill">${x.kind} · ${escapeHtml(x.paymentStatus||'pending')}</span><h3 style="margin:8px 0 4px">${escapeHtml(name)}</h3><span class="card-meta">${x.kind==='Rental'?new Date(x.startDate).toLocaleString('en-IN'):(formatDate(x.rideId?.date)+' · '+(x.rideId?.time||''))} · ${x.kind==='Rental'?x.hours+' hour(s)':x.seats+' seat(s)'}</span></div><div style="text-align:right"><b>₹${Number(x.totalAmount||0).toLocaleString('en-IN')}</b><br><span class="status">${escapeHtml(x.status)}</span>${x.paymentStatus==='paid'&&x.kind==='Rental'?`<br><button class="btn btn-outline" style="margin-top:8px;padding:8px 11px" data-download="${x.id}">Agreement</button>`:''}${canCancel?`<br><button class="btn btn-outline" style="margin-top:8px;padding:8px 11px;color:#b42318;border-color:#f0b7b2" data-cancel-kind="${x.kind}" data-cancel-id="${x.id}">Cancel</button>`:''}</div></article>`}).join(''):`<div class="empty">No ${status.toLowerCase()} bookings.</div>`;};
 const renderIncoming=()=>{const box=document.getElementById('incomingBookings');if(!box)return;box.innerHTML=incoming.length?incoming.map(x=>{const name=x.kind==='Incoming Rental'?(x.vehicleId?.name||'Vehicle'):`${x.rideId?.from||''} → ${x.rideId?.to||''}`;const canCancel=['pending','payment_pending','confirmed'].includes(x.status);return `<article class="booking-row"><div><span class="pill">${x.kind} · ${escapeHtml(x.paymentStatus||'pending')}</span><h3>${escapeHtml(name)}</h3><small>Customer: ${escapeHtml(x.userId?.name||'Passenger')} · ${x.kind==='Incoming Rental'?new Date(x.startDate).toLocaleString('en-IN'):formatDate(x.rideId?.date)}</small></div><div style="text-align:right"><b>₹${Number(x.totalAmount||0).toLocaleString('en-IN')}</b><br><span class="status">${escapeHtml(x.status)}</span>${canCancel?`<br><button class="btn btn-outline" style="margin-top:8px;padding:8px 11px;color:#b42318;border-color:#f0b7b2" data-incoming-kind="${x.kind}" data-incoming-id="${x.id}">Cancel</button>`:''}</div></article>`}).join(''):'<div class="empty">No bookings on your vehicles/rides yet.</div>';};
 render('Upcoming');renderIncoming();document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');render(t.textContent)}));
 el.addEventListener('click',async e=>{const d=e.target.closest('[data-download]');if(d)return downloadAgreement(d.dataset.download);const c=e.target.closest('[data-cancel-id]');if(!c)return;if(!confirm('Cancel this booking?'))return;try{const endpoint=c.dataset.cancelKind==='Rental'?'/bookings/':'/ride-bookings/';await api(endpoint+c.dataset.cancelId+'/cancel',{method:'POST',body:JSON.stringify({reason:'Cancelled from My Bookings'})});location.reload()}catch(err){alert(err.message)}});
 document.getElementById('incomingBookings')?.addEventListener('click',async e=>{const c=e.target.closest('[data-incoming-id]');if(!c)return;if(!confirm('Cancel this customer booking?'))return;try{const endpoint=c.dataset.incomingKind==='Incoming Rental'?'/bookings/':'/ride-bookings/';await api(endpoint+c.dataset.incomingId+'/cancel',{method:'POST',body:JSON.stringify({reason:'Cancelled by vehicle/ride owner'})});location.reload()}catch(err){alert(err.message)}});
 const agreements=await api('/bookings/my-agreements').catch(()=>[]);const ael=document.getElementById('agreementList');if(ael)ael.innerHTML=agreements.length?agreements.map(a=>`<article class="booking-row"><div><b>${escapeHtml(a.agreementId)}</b><br><small>Booking ${escapeHtml(a.bookingId)}</small></div><button class="btn btn-primary" data-download-agreement="${a.bookingId}">Download PDF</button></article>`).join(''):'<div class="empty">No agreements generated yet.</div>';ael?.addEventListener('click',e=>{const b=e.target.closest('[data-download-agreement]');if(b)downloadAgreement(b.dataset.downloadAgreement)});
});
